version: 2.1

machine:
  image: ubuntu-2204:2024.01.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Upgrade pip and install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r test_requirements.txt
      - run:
          name: Run tests with PYTHONPATH
          command: |
            PYTHONPATH=. pytest --junitxml=junit.xml
      - store_test_results:
          path: junit.xml

  docker_build:
    machine:
      image: ubuntu-2204:2024.01.2
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: make docker_build

workflows:
  basic:
    jobs:
      - build-and-test
      - docker_build:
          requires:
            - build-and-test
