version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10  
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install -r test_requirements.txt
      - run:
          name: Run tests
          command: pytest --junitxml=junit.xml
      - store_test_results:
          path: junit.xml

workflows:
  basic:
    jobs:
      - build-and-test
